create table
  public.global_inventory (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    gold integer null,
    total_red_ml integer not null default 0,
    total_green_ml integer not null default 0,
    total_blue_ml integer not null default 0,
    total_dark_ml integer not null default 0,
    total_ml integer null,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.potion_inventory (
    potion_id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    sku text not null,
    name text not null,
    quantity integer null,
    price integer null,
    num_red_ml integer null,
    num_green_ml integer null,
    num_blue_ml integer null,
    num_dark_ml integer null,
    constraint potion_inventory_pkey primary key (potion_id),
    constraint potion_inventory_name_key unique (name),
    constraint potion_inventory_sku_key unique (sku)
  ) tablespace pg_default;

create table
  public.customers (
    customer_id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text not null,
    class text not null,
    level integer not null,
    constraint customers_pkey primary key (customer_id)
  ) tablespace pg_default;

create table
  public.carts (
    cart_id bigint generated by default as identity,
    customer_id bigint null,
    created_at timestamp with time zone not null default now(),
    constraint carts_pkey primary key (cart_id),
    constraint carts_customer_id_fkey foreign key (customer_id) references customers (customer_id)
  ) tablespace pg_default;

create table
  public.cart_items (
    cart_item_id bigint generated by default as identity,
    cart_id bigint null,
    potion_id bigint null,
    quantity integer null,
    created_at timestamp with time zone not null default now(),
    constraint cart_items_pkey primary key (cart_item_id),
    constraint cart_items_cart_id_fkey foreign key (cart_id) references carts (cart_id),
    constraint cart_items_potion_id_fkey foreign key (potion_id) references potion_inventory (potion_id)
  ) tablespace pg_default;