create table
  public.cart_items (
    cart_item_id bigint generated by default as identity,
    cart_id bigint null,
    potion_id bigint null,
    quantity integer null,
    created_at timestamp with time zone not null default now(),
    constraint cart_items_pkey primary key (cart_item_id),
    constraint cart_items_cart_id_fkey foreign key (cart_id) references carts (cart_id),
    constraint cart_items_potion_id_fkey foreign key (potion_id) references potion_inventory (potion_id)
  ) tablespace pg_default;

create table
  public.carts (
    cart_id bigint generated by default as identity,
    customer_id bigint null,
    created_at timestamp with time zone not null default now(),
    constraint carts_pkey primary key (cart_id),
    constraint carts_customer_id_fkey foreign key (customer_id) references customers (customer_id)
  ) tablespace pg_default;

create table
  public.customers (
    customer_id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text not null,
    class text not null,
    level integer not null,
    constraint customers_pkey primary key (customer_id),
    constraint unique_customer unique (name, class, level)
  ) tablespace pg_default;

create table
  public.global_inventory (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    potion_capacity integer not null default 50,
    ml_capacity integer not null default 10000,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.gold_ledger (
    ledger_entry_id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    transaction_id bigint null,
    change integer not null,
    customer_id bigint null,
    constraint gold_ledger_pkey primary key (ledger_entry_id),
    constraint gold_ledger_customer_id_fkey foreign key (customer_id) references customers (customer_id),
    constraint gold_ledger_transaction_id_fkey foreign key (transaction_id) references transactions (transaction_id)
  ) tablespace pg_default;

create table
  public.ml_ledger (
    ledger_id bigint generated by default as identity,
    transaction_id bigint null,
    color text null,
    change integer not null,
    created_at timestamp with time zone not null default now(),
    constraint ml_ledger_pkey primary key (ledger_id),
    constraint ml_ledger_transaction_id_fkey foreign key (transaction_id) references transactions (transaction_id)
  ) tablespace pg_default;

create table
  public.potion_inventory (
    potion_id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    sku text not null,
    name text not null,
    price integer null,
    num_red_ml integer null,
    num_green_ml integer null,
    num_blue_ml integer null,
    num_dark_ml integer null,
    constraint potion_inventory_pkey primary key (potion_id),
    constraint potion_inventory_name_key unique (name),
    constraint potion_inventory_sku_key unique (sku)
  ) tablespace pg_default;

create table
  public.potion_ledger (
    ledger_id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    transaction_id bigint not null,
    customer_id bigint null,
    change integer not null,
    potion_id bigint not null,
    constraint potion_ledger_pkey primary key (ledger_id),
    constraint potion_ledger_customer_id_fkey foreign key (customer_id) references customers (customer_id),
    constraint potion_ledger_potion_id_fkey foreign key (potion_id) references potion_inventory (potion_id),
    constraint potion_ledger_transaction_id_fkey foreign key (transaction_id) references transactions (transaction_id)
  ) tablespace pg_default;

create table
  public.transactions (
    transaction_id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    description text not null,
    constraint transactions_pkey primary key (transaction_id)
  ) tablespace pg_default;